// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using crmvcsb.Infrastructure.EF.costControl;

namespace crmvcsb.Migrations.CostControll
{
    [DbContext(typeof(CostControllContext))]
    partial class CostControllContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("crmvcsb.Domain.TestModels.Models.CostControl.BusinessColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id_Business_Column")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnName("Code");

                    b.Property<string>("Comment")
                        .HasColumnName("Code");

                    b.Property<string>("Name")
                        .HasColumnName("Name");

                    b.Property<string>("ShortName")
                        .HasColumnName("ShortName");

                    b.Property<int>("StatusId")
                        .HasColumnName("Status_Id");

                    b.Property<string>("UseInPaymentsRequest")
                        .HasColumnName("Is_Use_In_Request");

                    b.HasKey("Id");

                    b.ToTable("Business_Columns","dic");
                });

            modelBuilder.Entity("crmvcsb.Domain.TestModels.Models.CostControl.BusinessLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id_Business_Line")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BusinessColumnId");

                    b.Property<string>("Code")
                        .HasColumnName("Code");

                    b.Property<string>("Comment")
                        .HasColumnName("Code");

                    b.Property<string>("Name")
                        .HasColumnName("Name");

                    b.Property<string>("ShortName")
                        .HasColumnName("ShortName");

                    b.Property<int>("StatusId")
                        .HasColumnName("Status_Id");

                    b.Property<string>("UseInPaymentsRequest")
                        .HasColumnName("Is_Use_In_Request");

                    b.HasKey("Id");

                    b.HasIndex("BusinessColumnId");

                    b.ToTable("Business_Lines","dic");
                });

            modelBuilder.Entity("crmvcsb.Domain.TestModels.Models.CostControl.BusinessLine", b =>
                {
                    b.HasOne("crmvcsb.Domain.TestModels.Models.CostControl.BusinessColumn", "BusinessColumn")
                        .WithMany("BusinessLines")
                        .HasForeignKey("BusinessColumnId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
